# Generated by Django 2.2 on 2021-04-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCollectionArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('bc_inventory_number', models.CharField(max_length=1024)),
                ('bc_date_acquired', models.CharField(max_length=256)),
                ('bc_change_user', models.CharField(max_length=256)),
                ('bc_change_date', models.CharField(max_length=256)),
                ('bc_dating', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('first_name', models.CharField(default='', max_length=1024)),
                ('last_name', models.CharField(default='', max_length=1024)),
                ('alias_name', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCollectionObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('bc_id', models.IntegerField()),
                ('bc_inventory_number', models.CharField(blank=True, default='', max_length=1024)),
                ('bc_change_user', models.CharField(blank=True, default='', max_length=256)),
                ('bc_change_date', models.CharField(blank=True, default='', max_length=256)),
                ('bc_object_name', models.CharField(blank=True, default='', max_length=256)),
                ('bc_images', models.CharField(blank=True, default='', max_length=1024)),
                ('bc_image_license', models.CharField(blank=True, default='', max_length=256)),
                ('bc_notes', models.CharField(blank=True, default='', max_length=4024)),
                ('bc_credits', models.CharField(blank=True, default='', max_length=1024)),
                ('bc_tags', models.CharField(blank=True, default='', max_length=1024)),
                ('tag_synonyms', models.CharField(default='', max_length=10000)),
                ('publications', models.CharField(blank=True, default='', max_length=1024)),
                ('date_acquired', models.CharField(blank=True, default='', max_length=256)),
                ('datings', models.CharField(blank=True, default='', max_length=1024)),
                ('dating_from_df', models.DateField(blank=True, null=True)),
                ('dating_to_df', models.DateField(blank=True, null=True)),
                ('provenance', models.CharField(blank=True, default='', max_length=1024)),
                ('is_highlight', models.BooleanField(default=False)),
                ('convolute', models.CharField(blank=True, default='', max_length=256)),
                ('series_id', models.CharField(blank=True, max_length=256, null=True)),
                ('container_name', models.CharField(blank=True, default='', max_length=1024)),
                ('container_id', models.CharField(blank=True, default='', max_length=256)),
                ('current_location', models.CharField(blank=True, default='', max_length=256)),
                ('geographic_location', models.CharField(blank=True, default='', max_length=1024)),
                ('title', models.CharField(blank=True, default='', max_length=1024, verbose_name='Titel')),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('signatures', models.CharField(blank=True, default='', max_length=1024, verbose_name='Signatur')),
                ('object_type', models.CharField(blank=True, default='', max_length=1024, verbose_name='Objektbezeichnung')),
                ('material', models.CharField(blank=True, max_length=1024)),
                ('dimensions', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=4096)),
            ],
            options={
                'verbose_name': 'Paginacategorie',
                'verbose_name_plural': 'Paginacategorieen',
            },
        ),
        migrations.CreateModel(
            name='CollectionObjectSeriesTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionObjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_img_link', to='collection.BaseCollectionObject')),
            ],
        ),
    ]
