# Generated by Django 2.2 on 2021-06-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecollectionobject',
            name='geographic_reference',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
