# Generated by Django 2.2 on 2021-04-23 17:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectimagelink',
            name='object_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_img_link', to='core.metahubImage'),
        ),
        migrations.AddField(
            model_name='collectionobjecttag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_objects', to='core.MetaHubObjectPage'),
        ),
        migrations.AddField(
            model_name='collectionobjecttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_collectionobjecttag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='collectionobjectseriestag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_object_series', to='core.MetaHubObjectSeriesPage'),
        ),
        migrations.AddField(
            model_name='collectionobjectseriestag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_collectionobjectseriestag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='basecollectionobject',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.BaseCollectionArtist', verbose_name='Künstler'),
        ),
        migrations.AddField(
            model_name='basecollectionobject',
            name='bc_tags_separate',
            field=models.ManyToManyField(blank=True, related_name='attached_objects', to='collection.BaseTag'),
        ),
        migrations.AddField(
            model_name='basecollectionobject',
            name='series_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_objects', to='core.MetaHubObjectSeriesPage'),
        ),
    ]
