# Generated by Django 3.1.12 on 2021-06-23 16:08

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_basecollectionobject_geographic_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahubcategoryoverviewpage',
            name='theme_color',
            field=models.CharField(choices=[('magenta', 'Magenta pink'), ('strawberry', 'Strawberry red'), ('sapphire', 'Sapphire blue'), ('phlox', 'Phlox purple')], default='magenta', max_length=100),
        ),
        migrations.AddField(
            model_name='metahubobjectpage',
            name='theme_color',
            field=models.CharField(choices=[('magenta', 'Magenta pink'), ('strawberry', 'Strawberry red'), ('sapphire', 'Sapphire blue'), ('phlox', 'Phlox purple')], default='magenta', max_length=100),
        ),
        migrations.AddField(
            model_name='metahubobjectseriespage',
            name='theme_color',
            field=models.CharField(choices=[('magenta', 'Magenta pink'), ('strawberry', 'Strawberry red'), ('sapphire', 'Sapphire blue'), ('phlox', 'Phlox purple')], default='magenta', max_length=100),
        ),
        migrations.AlterField(
            model_name='metahubobjectpage',
            name='content',
            field=wagtail.core.fields.StreamField([], blank=True),
        ),
        migrations.AlterField(
            model_name='metahubobjectseriespage',
            name='content',
            field=wagtail.core.fields.StreamField([], blank=True),
        ),
    ]
