# Generated by Django 3.1.12 on 2021-06-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('collection', '0003_auto_20210623_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metahubobjectpage',
            name='theme_color',
            field=models.CharField(choices=[('theme--magenta', 'Magenta pink'), ('theme--pink', 'Strawberry red'), ('theme--blue', 'Sapphire blue'), ('theme--purple', 'Phlox purple')], default='theme--magenta', max_length=100),
        ),
        migrations.AlterField(
            model_name='metahubobjectseriespage',
            name='theme_color',
            field=models.CharField(choices=[('theme--magenta', 'Magenta pink'), ('theme--pink', 'Strawberry red'), ('theme--blue', 'Sapphire blue'), ('theme--purple', 'Phlox purple')], default='theme--magenta', max_length=100),
        ),
        migrations.DeleteModel(
            name='MetaHubCategoryOverviewPage',
        ),
    ]
