# Generated by Django 3.1.12 on 2021-08-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('locations', '0003_metahublocationpage_tags'),
        ('collection', '0008_auto_20210716_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahubobjectpage',
            name='location_page',
            field=models.ManyToManyField(blank=True, null=True, related_name='object_pages', to='locations.MetaHubLocationPage'),
        ),
    ]
