# Generated by Django 3.1.12 on 2021-08-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_metahubobjectpage_location_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metahubobjectpage',
            name='location_page',
        ),
    ]
