# Generated by Django 3.1.12 on 2021-09-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20210907_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecollectionartist',
            name='bc_dating',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='basecollectionartist',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
