# Generated by Django 3.2 on 2021-06-21 13:43

from django.db import migrations
import starling.mixins
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahubcontentpage',
            name='text_header',
            field=wagtail.core.fields.StreamField([('header_text', wagtail.core.blocks.StructBlock([]))], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metahubcontentpage',
            name='content',
            field=wagtail.core.fields.StreamField([('single_richtext', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock())])), ('single_image', wagtail.core.blocks.StructBlock([('figure', wagtail.core.blocks.StructBlock([('picture', wagtail.core.blocks.StructBlock([('source', wagtail.images.blocks.ImageChooserBlock())], resolution=('1920', '', '', '', '', '', True, True, False))), ('caption', wagtail.core.blocks.CharBlock(required=False))]))])), ('double_picture_richtext', wagtail.core.blocks.StructBlock([('figure', wagtail.core.blocks.StructBlock([('picture', wagtail.core.blocks.StructBlock([('source', wagtail.images.blocks.ImageChooserBlock())])), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('text', wagtail.core.blocks.RichTextBlock(required=True)), ('link', starling.mixins.OptionalBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('href', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('external', wagtail.core.blocks.URLBlock()), ('mail', wagtail.core.blocks.EmailBlock()), ('phone', wagtail.core.blocks.CharBlock())], max_num=1, min_num=1))]))])))]))]),
        ),
        migrations.AlterField(
            model_name='metahubcontentpage',
            name='hero_header',
            field=wagtail.core.fields.StreamField([('header_image', wagtail.core.blocks.StructBlock([]))]),
        ),
    ]
