# Generated by Django 3.1.12 on 2021-09-07 19:01

from django.db import migrations, models
import starling.mixins
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailstreamforms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210628_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metahubcontentpage',
            name='content',
            field=wagtail.core.fields.StreamField([('single_richtext', wagtail.core.blocks.StructBlock([('id', wagtail.core.blocks.CharBlock(help_text='Optional, to use as an anchor in the page', max_length=100, required=False)), ('text', wagtail.core.blocks.RichTextBlock())])), ('two_column_picture_richtext', wagtail.core.blocks.StructBlock([('id', wagtail.core.blocks.CharBlock(help_text='Optional, to use as an anchor in the page', max_length=100, required=False)), ('figure', wagtail.core.blocks.StructBlock([('picture', wagtail.core.blocks.StructBlock([('source', wagtail.images.blocks.ImageChooserBlock())], crop=False, resolution=('4096', '', '', '', '', '', True, True, False))), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('text', wagtail.core.blocks.RichTextBlock(required=True))])), ('richtext_with_link', wagtail.core.blocks.StructBlock([('id', wagtail.core.blocks.CharBlock(help_text='Optional, to use as an anchor in the page', max_length=100, required=False)), ('text', wagtail.core.blocks.RichTextBlock(required=True)), ('link', starling.mixins.OptionalBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('href', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('external', wagtail.core.blocks.URLBlock()), ('mail', wagtail.core.blocks.EmailBlock()), ('phone', wagtail.core.blocks.CharBlock())], max_num=1, min_num=1))]))])))])), ('video', wagtail.core.blocks.StructBlock([('id', wagtail.core.blocks.CharBlock(help_text='Optional, to use as an anchor in the page', max_length=100, required=False)), ('video', wagtail.core.blocks.StructBlock([('video', wagtail.core.blocks.StructBlock([('src', wagtail.core.blocks.StreamBlock([('youtube', wagtail.core.blocks.StructBlock([('src', wagtail.core.blocks.URLBlock(role='source')), ('title', wagtail.core.blocks.CharBlock(role='title'))])), ('vimeo', wagtail.core.blocks.StructBlock([('src', wagtail.core.blocks.URLBlock(role='source')), ('title', wagtail.core.blocks.CharBlock(role='title'))]))], max_num=1, min_num=1))])), ('picture', wagtail.core.blocks.StructBlock([('source', wagtail.images.blocks.ImageChooserBlock())], resolution=('1080x1050', '', '', '', '', '', True, True, False)))], required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('highlight', wagtail.core.blocks.StructBlock([('id', wagtail.core.blocks.CharBlock(help_text='Optional, to use as an anchor in the page', max_length=100, required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=200)), ('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('href', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('external', wagtail.core.blocks.URLBlock()), ('mail', wagtail.core.blocks.EmailBlock()), ('phone', wagtail.core.blocks.CharBlock())], max_num=1, min_num=1))]))])), ('picture', wagtail.core.blocks.StructBlock([('source', wagtail.images.blocks.ImageChooserBlock())], resolution=('4096', '', '', '', '', '', False, True, False)))])), ('image_mosaic', wagtail.core.blocks.StructBlock([('id', wagtail.core.blocks.CharBlock(help_text='Optional, to use as an anchor in the page', max_length=100, required=False)), ('figures', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('picture', wagtail.core.blocks.StructBlock([('source', wagtail.images.blocks.ImageChooserBlock())], crop=False, resolution=('4096', '', '', '', '', '', True, True, False))), ('caption', wagtail.core.blocks.CharBlock(required=False))])))])), ('sponsor_logos', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('text', wagtail.core.blocks.TextBlock(label='Text', required=False)), ('variant', wagtail.core.blocks.ChoiceBlock(choices=[('default', 'Default'), ('large', 'Large')], label='Sponsors size')), ('logos', wagtail.core.blocks.StreamBlock([('logo', wagtail.core.blocks.StructBlock([('picture', wagtail.core.blocks.StructBlock([('source', wagtail.images.blocks.ImageChooserBlock())], resolution=('160x80', '', '', '', '', '', False, True, False))), ('size_percentage', wagtail.core.blocks.ChoiceBlock(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90)], label='Size in percentage', required=False)), ('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('href', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('external', wagtail.core.blocks.URLBlock()), ('mail', wagtail.core.blocks.EmailBlock()), ('phone', wagtail.core.blocks.CharBlock())], max_num=1, min_num=1))]))]))]))], default=[], label='Logos', required=False))])), ('places_map', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('link_borneplatz_href_block', wagtail.core.blocks.PageChooserBlock()), ('link_alter_href_block', wagtail.core.blocks.PageChooserBlock()), ('link_toraschrein_href_block', wagtail.core.blocks.PageChooserBlock())])), ('cookie_settings', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock())])), ('form', wagtail.core.blocks.StructBlock([('form', wagtailstreamforms.blocks.FormChooserBlock()), ('form_action', wagtail.core.blocks.CharBlock(help_text='The form post action. "" or "." for the current page or a url', required=False)), ('form_reference', wagtailstreamforms.blocks.InfoBlock(help_text='This form will be given a unique reference once saved', required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='metahubcontentpage',
            name='hero_header',
            field=wagtail.core.fields.StreamField([('header_image', wagtail.core.blocks.StructBlock([('picture', wagtail.core.blocks.StructBlock([('source', wagtail.images.blocks.ImageChooserBlock())], resolution=('4096x2160', '', '', '', '', '', True, True, False)))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='metahubcontentpage',
            name='text_header',
            field=wagtail.core.fields.StreamField([('header_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200)), ('text', wagtail.core.blocks.TextBlock(max_length=2000, required=False))]))]),
        ),
        migrations.AlterField(
            model_name='metahubcontentpage',
            name='theme_color',
            field=models.CharField(choices=[('theme--pink', 'Magenta pink'), ('theme--magenta', 'Strawberry red'), ('theme--blue', 'Sapphire blue'), ('theme--purple', 'Royal purple')], default='theme--pink', max_length=100),
        ),
    ]
