# Generated by Django 3.1.8 on 2021-04-13 17:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='actions',
            field=wagtail.core.fields.StreamField([('mail_action', wagtail.core.blocks.StructBlock([('email_address', wagtail.core.blocks.EmailBlock('Receiver'))]))], blank=True, verbose_name='Actions'),
        ),
    ]
