# Generated by Django 3.1.12 on 2021-09-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0002_form_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='template_name',
            field=models.CharField(choices=[('streamforms/form_block.html', 'Default Form Template')], default='streamforms/form_block.html', max_length=255, verbose_name='Template'),
        ),
    ]
