# Generated by Django 3.1.12 on 2021-09-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overviews', '0003_auto_20210628_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metahuboverviewpage',
            name='theme_color',
            field=models.CharField(choices=[('theme--pink', 'Magenta pink'), ('theme--magenta', 'Strawberry red'), ('theme--blue', 'Sapphire blue'), ('theme--purple', 'Royal purple')], default='theme--pink', max_length=100),
        ),
    ]
