# Generated by Django 2.2 on 2020-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeeCollectSyncOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_done', models.DateTimeField(auto_now_add=True)),
                ('date_data_dump', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('items_in_dump', models.PositiveIntegerField()),
                ('items_added', models.PositiveIntegerField()),
                ('items_changed', models.PositiveIntegerField()),
                ('items_removed', models.PositiveIntegerField()),
            ],
        ),
    ]
