# Generated by Django 2.2 on 2021-06-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeeCollectSyncOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_done', models.DateTimeField(auto_now_add=True)),
                ('date_data_dump', models.CharField(max_length=1000)),
                ('success', models.BooleanField(default=False)),
                ('objects_in_dump', models.PositiveIntegerField(default=0)),
                ('objects_added', models.PositiveIntegerField(default=0)),
                ('objects_changed', models.PositiveIntegerField(default=0)),
                ('objects_removed', models.PositiveIntegerField(default=0)),
                ('artists_in_dump', models.PositiveIntegerField(default=0)),
                ('artists_added', models.PositiveIntegerField(default=0)),
                ('artists_changed', models.PositiveIntegerField(default=0)),
                ('artists_removed', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
