# Generated by Django 3.1.12 on 2021-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beecollectsyncoccurrence',
            name='museum',
            field=models.CharField(default='', max_length=3),
        ),
    ]
