# Generated by Django 2.2 on 2020-06-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beecollectsyncoccurrence',
            name='date_data_dump',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='beecollectsyncoccurrence',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
