# Generated by Django 2.2 on 2020-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20200629_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='beecollectsyncoccurrence',
            name='artists_added',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beecollectsyncoccurrence',
            name='artists_changed',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beecollectsyncoccurrence',
            name='artists_in_dump',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beecollectsyncoccurrence',
            name='artists_removed',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
