# Generated by Django 2.2 on 2020-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20200629_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beecollectsyncoccurrence',
            name='artists_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beecollectsyncoccurrence',
            name='artists_changed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beecollectsyncoccurrence',
            name='artists_in_dump',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beecollectsyncoccurrence',
            name='artists_removed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beecollectsyncoccurrence',
            name='items_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beecollectsyncoccurrence',
            name='items_changed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beecollectsyncoccurrence',
            name='items_in_dump',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beecollectsyncoccurrence',
            name='items_removed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
