# Generated by Django 2.2 on 2020-06-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_auto_20200629_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beecollectsyncoccurrence',
            old_name='items_added',
            new_name='objects_added',
        ),
        migrations.RenameField(
            model_name='beecollectsyncoccurrence',
            old_name='items_changed',
            new_name='objects_changed',
        ),
        migrations.RenameField(
            model_name='beecollectsyncoccurrence',
            old_name='items_in_dump',
            new_name='objects_in_dump',
        ),
        migrations.RenameField(
            model_name='beecollectsyncoccurrence',
            old_name='items_removed',
            new_name='objects_removed',
        ),
    ]
