# Generated by Django 3.1.12 on 2021-06-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahubnewspage',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='news_articles', to='authors.Author'),
        ),
        migrations.AddField(
            model_name='metahubnewspage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
