# Generated by Django 3.1.12 on 2021-06-23 11:00

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('news', '0002_auto_20210623_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metahubnewspage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, related_name='news_articles', to='authors.Author'),
        ),
    ]
