# Generated by Django 3.1.12 on 2021-06-23 11:10

from django.db import migrations
import wagtail.core.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210623_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metahubnewspage',
            name='authors',
        ),
        migrations.AddField(
            model_name='metahubnewspage',
            name='authors',
            field=wagtail.core.fields.StreamField([('author', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='authors.author'))], blank=True),
        ),
    ]
