# Generated by Django 3.1.12 on 2021-06-23 16:07

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210623_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahubnewspage',
            name='theme_color',
            field=models.CharField(choices=[('magenta', 'Magenta pink'), ('strawberry', 'Strawberry red'), ('sapphire', 'Sapphire blue'), ('phlox', 'Phlox purple')], default='magenta', max_length=100),
        ),
        migrations.AlterField(
            model_name='metahubnewspage',
            name='related_items',
            field=wagtail.core.fields.StreamField([('related_curated', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100)), ('items', wagtail.core.blocks.StructBlock([('pages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(required=False)))]))])), ('related_automatic', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100))]))], blank=True),
        ),
    ]
