# Generated by Django 3.1.3 on 2021-02-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_mail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='text',
            field=models.TextField(),
        ),
    ]
