# Generated by Django 3.1.3 on 2021-03-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_auto_20210211_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='key',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
