# Generated by Django 3.1.12 on 2021-07-01 14:20

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210628_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahubhomepage',
            name='home_intro',
            field=wagtail.core.fields.StreamField([('home_intro', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200)), ('text', wagtail.core.blocks.RichTextBlock(features=['link']))]))], default=''),
            preserve_default=False,
        ),
    ]
