# Generated by Django 3.1.12 on 2021-07-01 16:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_metahubhomepage_object_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahubhomepage',
            name='story_highlight',
            field=wagtail.core.fields.StreamField([('story_highlight', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100)), ('featured_item', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(page_type=['stories.MetaHubStoryPage'], required=False))])), ('excerpt', wagtail.core.blocks.TextBlock()), ('link_label', wagtail.core.blocks.CharBlock(default='Read more', max_length=200))]))], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metahubhomepage',
            name='object_highlights',
            field=wagtail.core.fields.StreamField([('object_highlights', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100)), ('items', wagtail.core.blocks.StructBlock([('pages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(page_type=['collection.MetaHubObjectPage'], required=False)))]))], defaults={'classes': 'relevant-objects--home'}))]),
        ),
    ]
