# Generated by Django 2.2 on 2020-06-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
    ]
