# Generated by Django 3.1.12 on 2021-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='de', max_length=200),
            preserve_default=False,
        ),
    ]
