# Generated by Django 3.1.12 on 2021-08-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('menu', '0002_menu_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
    ]
