# Generated by Django 2.2 on 2020-06-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200605_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='custom_link_value',
            field=models.CharField(blank=True, help_text='Only needed for custom menu items', max_length=63, verbose_name='Custom value'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon_after',
            field=models.CharField(choices=[('', 'None'), ('custom/ic_slash', 'slash'), ('custom/heart-icon', 'heart')], default='', max_length=15, verbose_name='Icon after'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon_before',
            field=models.CharField(choices=[('', 'None'), ('custom/ic_slash', 'slash'), ('custom/heart-icon', 'heart')], default='', max_length=15, verbose_name='Icon before'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('page', 'Page'), ('custom', 'Custom')], default='page', max_length=15, verbose_name='Type'),
        ),
    ]
