# Generated by Django 2.2 on 2020-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200611_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='icon_after',
            field=models.CharField(blank=True, choices=[('', 'None'), ('custom/ic_slash', 'slash'), ('custom/heart-icon', 'heart')], default='', max_length=15, verbose_name='Icon after'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon_before',
            field=models.CharField(blank=True, choices=[('', 'None'), ('custom/ic_slash', 'slash'), ('custom/heart-icon', 'heart')], default='', max_length=15, verbose_name='Icon before'),
        ),
    ]
