# Generated by Django 2.2 on 2020-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200821_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='icon_after',
            field=models.CharField(blank=True, choices=[('', 'None'), ('custom/ic_slash', 'slash'), ('custom/heart-icon', 'heart'), ('custom/ic_search', 'search')], default='', max_length=25, verbose_name='Icon after'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon_before',
            field=models.CharField(blank=True, choices=[('', 'None'), ('custom/ic_slash', 'slash'), ('custom/heart-icon', 'heart'), ('custom/ic_search', 'search')], default='', max_length=25, verbose_name='Icon before'),
        ),
    ]
