# Generated by Django 3.2 on 2021-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=4096)),
            ],
            options={
                'verbose_name': 'Paginacategorie',
                'verbose_name_plural': 'Paginacategorieen',
            },
        ),
    ]
