# Generated by Django 3.1.12 on 2021-07-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionCategory',
        ),
    ]
