# Generated by Django 3.2 on 2021-04-30 16:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetahubImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailimages.image')),
                ('alt_text', models.CharField(blank=True, help_text='Optionele beschrijving van wat er in de afbeelding te zien is.', max_length=150, verbose_name='Alt tekst')),
                ('attribution', models.CharField(blank=True, help_text='Artist credit or licensing information, leave blank if not applicable', max_length=4000, verbose_name='Credit')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailimages.image',),
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_site_description', models.CharField(blank=True, help_text="Beschrijving van de site voor zoekmachine's e.d.", max_length=300, verbose_name='Meta description')),
                ('footer_content_simple', wagtail.core.fields.StreamField([('footer', wagtail.core.blocks.StructBlock([('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('href', wagtail.core.blocks.StructBlock([('source', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('external', wagtail.core.blocks.URLBlock()), ('mail', wagtail.core.blocks.EmailBlock()), ('phone', wagtail.core.blocks.CharBlock())], max_num=1, min_num=1))]))])))]))])),
                ('default_share_image', models.ForeignKey(blank=True, help_text="Afbeelding voor op Facebook e.d. voor pagina's die zelf geen afbeelding hebben.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.metahubimage', verbose_name='Standaard share image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Algemene instellingen',
                'verbose_name_plural': 'Algemene instellingen',
            },
        ),
    ]
